<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8"/>
    <title>可视化页面编辑器</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>    
    <link rel="stylesheet" href="pkg/npm_deps_592c5ff.css" />
    <link rel="stylesheet" type="text/css" href="scss/style_e8ad8df.css" />
</head>

<body>
<div id="root" class="app-wrapper"></div>
<script src="mod_3f80d17.js"></script>
<script type="text/javascript" src="pkg/index.html_map_8981329.js"></script>
<script type="text/javascript" src="pkg/npm_deps_f8d2a87.js"></script>
<script type="text/javascript" src="store/Page_6797a7c.js"></script>
<script type="text/javascript" src="store/index_be9eb73.js"></script>
<script type="text/javascript" src="route/index_bfd5e02.js"></script>
<script type="text/javascript" src="api/SchemaApi_df4c439.js"></script>
<script type="text/javascript" src="App_b1dd293.js"></script>
<script type="text/javascript" src="index_4cc28b3.js"></script>
<script src="jsrsasign-all-min_ba78b21.js"></script>
<script type="text/javascript">
    var _hmt = _hmt || [];

    /* @require index.tsx 标记为同步依赖，提前加载 */
    amis.require(['index.tsx'], function (app) {
        var initialState = {};
        app.bootstrap(document.getElementById('root'), initialState);
    });
</script>
</body>

</html>
